// <auto-generated />
namespace IAAI0731.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class ini : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ini));
        
        string IMigrationMetadata.Id
        {
            get { return "202408030858586_ini"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
